language: bash
services: docker
before_install: 
  - cd 18\ RestWithSpringBootUdemy\ -\ AWS
  - echo "We are in the Docker folder!"
script:
  - docker-compose build
before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
deploy:
  provider: script
  script: 
    docker push devthiagofurtado/rest-with-spring-boot-udemy;
    docker push devthiagofurtado/mysql-rest-with-spring-boot-udemy;
  on:
    branch: main
notifications:
  email: false    