version: '3.4'
services:
  db:
    image: mysql:8.0.28
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker123
      MYSQL_DATABASE: springboot_udemy
    ports:
      - "3308:3306"
    networks:
      - udemy-network
  rest-with-spring-boot-udemy:
    image: rest-with-spring-boot-udemy
    restart: always
    build: ./RestWithSpringBootUdemy
    working_dir: /RestWithSpringBootUdemy
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    ports:
      - "8080:8080"
    command: mvn spring-boot:run
    links:
      - mvn
    depends_on:
      - db
    networks:
      - udemy-network
networks:
  udemy-network:
    driver: bridge