spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://restwithspringbootudemy.c0l8ee79uqwp.us-east-1.rds.amazonaws.com/rest_with_spring_boot_udemy
    username: docker
    password: docker123
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect